### ISSUE TITLE
validator.body is not a function

### ISSUE THREAD

**Issue by enbermudas** [evanshortiss/express-joi-validation#16]
I'm getting the next error:

```
TypeError: validator.body is not a function
    at Object.<anonymous> (c:\sandbox\node\node-bulletin-board\routes\auth.routes.js:7:36)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (c:\sandbox\node\node-bulletin-board\routes\index.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (c:\sandbox\node\node-bulletin-board\config\express.config.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (c:\sandbox\node\node-bulletin-board\index.js:2:13)
```
While using the library to validate the incoming request body:

```
const validator = require('express-joi-validation');
const schema = require('../schemas/auth.schema');
router.post('/register', validator.body(schema.register), controller.register);
```

**Comment by evanshortiss** [comment]
@enbermudas looks like you didn't create a validator instance.

Change this...

```js
// This is actually referencing the factory, but not invoking it to get an instance
const validator = require('express-joi-validation');
```

to this...

```js
// This invokes the validator factory to create an instance
const validator = require('express-joi-validation')();
```

Feel free to reopen this issue if the solution doesn't work 😄
